### ISSUE TITLE
System audio source does not work

### ISSUE THREAD

**Issue by joeycode2** [MineAndCraft12/AaronOS_Music#1]
It makes an outline of a rectangle and than nothing else.
![image](https://user-images.githubusercontent.com/37389826/75118055-2e1e8500-563c-11ea-8d2e-ef5ce8336d42.png)

**Comment by MineAndCraft12** [comment]
@joeycode2 Does version 1.7 fix the issue?

**Comment by MineAndCraft12** [comment]
The issue is fixed on my end with multi-monitor setup.
